(update-metadata.ps1) Adding File & Dependency with tests
WormieCorp/Wormies-AU-Helpers pull request #33
Opened 2020-08-20 21:13 UTC by RedBaron2

@AdmiringWorm 
This is the newest update to the metadata function. This will do file/dependency and multiples of file/dependency if found in the nuspec file. 
It will not currently

- Add New Key/Element to the nuspec

- Update a file/dependency key that doesn't have any attribute defined `<file />` or `<dependency />`

Throws have been redone as warnings mainly to **_not stop_** the entire line from completing
`@{ id = "My Custom S iD";  dependency = 'kb2919355,1.0.20190915'; title = "My Custom X Title"; docs "http://SomeURI/folder/folder1/documentation" } | Update-Metadata`

2020-08-20 21:30 UTC, RedBaron2 commented
@AdmiringWorm 
I'll need to work on improving the tests to reach closer to 99.99%

2020-08-20 21:36 UTC, RedBaron2 commented
temp Close so Appveyor doesn't start a partial Run

2020-08-21 02:19 UTC, RedBaron2 commented
reopen to run new tests for higher codecov reporting

2020-08-25 17:44 UTC, RedBaron2 commented
@AdmiringWorm 
Until some feed back is given I'll pursue other projects

2020-08-26 04:31 UTC, AdmiringWorm commented
@RedBaron2 I will be gone for the rest of the week, but will be back next week.
If you could remind me sometime next week I should be able to give you some feedback/review then.

2020-08-26 04:53 UTC, RedBaron2 commented
@AdmiringWorm 
I'll make a event for that next week
Enjoy the time away

2020-09-03 02:28 UTC, RedBaron2 commented
@AdmiringWorm 
Heads-up of your reminder to review.
Thanks

2020-09-03 04:20 UTC, AdmiringWorm commented
@RedBaron2 it is on my list, have a couple of other things that I need to do first (so expect a review on Saturday or Sunday).

2020-09-07 08:52 UTC, AdmiringWorm requested changes
In general, the changes look good.
But please update the style of the code to the following a similar path that I already use in other helpers.

Please also split lines that are longer than 120 characters to multiple lines.

2020-09-07 08:52 UTC, AdmiringWorm commented on Wormies-AU-Helpers/public/Update-Metadata.ps1
> +        [hashtable]$data = [ordered] @{$key = $value},
Do this really need the `[ordered]` attribute?
If not, please remove it.

2020-09-07 08:52 UTC, AdmiringWorm commented on Wormies-AU-Helpers/public/Update-Metadata.ps1
> +                $NodeCount = $nu.package.$metaData.ChildNodes.Count; $src,$target,$exclude = $NodeData -split ("\|")
please split this line to multiple lines (ie, don't use `;`)

2020-09-07 08:52 UTC, AdmiringWorm commented on Wormies-AU-Helpers/public/Update-Metadata.ps1
> +                $NodeAttributes = [ordered] @{"src" = $src;"target" = $target;"exclude" = $exclude}
please split the hash table over multiple lines, instead of using `;`

2020-09-07 08:52 UTC, AdmiringWorm commented on Wormies-AU-Helpers/public/Update-Metadata.ps1
> +                if ($NodeCount -eq 3) { $NodeGroup = $NodeGroup."$_"; $omitted = $true } else { $NodeGroup = $NodeGroup.$_[$change] }
Please follow the already code convention, `if` statements should not be on a single line.

2020-09-07 16:58 UTC, RedBaron2 commented
I'll work on the changes and update the files

2020-10-09 22:57 UTC, RedBaron2 commented
@AdmiringWorm 
I think everything is ready for you to look at this again when you have the time. 😁

2021-01-04 20:21 UTC, AdmiringWorm commented
I am sorry to have gone quiet for so long, had to go offline due to health problems.
I am now circling back to issues that have been opened since October that I never responded to/neglected during this time.

I have this pull request specifically on my list of todo items to complete this month, but need to go through the other notifications and messages I have received in the past few months.

2021-01-31 11:09 UTC, AdmiringWorm approved these changes
LGTM

2021-01-31 11:10 UTC, merged

2021-01-31 11:12 UTC, AdmiringWorm commented
@RedBaron2 your changes have been merged, thanks for your contribution 👍